[package]
name = "alrust2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
serde_json = "1.0.91"

genetic = { path="genetic" }
geneticalchemy = { path="geneticalchemy" }
grimoire2 = { path="grimoire2" }
grimoire-sqlite = { path="grimoire-sqlite" }


[workspace]
members = [
    'genetic',
    'geneticalchemy',
    'grimoire-sqlite',
]


[features]
json = []