[package]
name = "alrust2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.149", features = ["derive"]}
serde_yaml = "0.9.14"
thiserror = "1.0.37"
anyhow = "1.0.66"
clap = "4.0.29"
float-cmp = "0.9.0"
error-stack = "0.2.4"
diesel = {version = "2.0.2", features = ["sqlite"]}
diesel_migrations = "2.0.0"
evalexpr = {version="8.1.0", features = ["serde_support"]}
rand = {version="0.8.5", features=["small_rng"]}
chrono = "0.4.23"
rusqlite = { version = "0.28.0", features = ["bundled"] }

genetic = { path="genetic" }
geneticalchemy = { path="geneticalchemy" }
grimoire = { path="grimoire" }


[workspace]
members = [
    'genetic',
    'grimoire',
    'geneticalchemy'
]
