population_size: 100
output_every: 5000
character: default

grimoire:
   db: ../new.sqlite

mutate:
   amount_grow_ratio: 0.25
   min_amount_grow: 1
   num_mutations_amt: 8
   num_mutations_ing: 2

effects:
   - hot
   - hl

include_ingredients: hot > 0 || mhot > 0 || hl > 0 || mhl > 0