population_size: 100
output_every: 10000
db_name: "../db.sqlite"

mutate:
   amount_grow_ratio: 0.25
   min_amount_grow: 1
   num_mutations_amt: 8
   num_mutations_ing: 2

desired_effects:
   - MaximizeHOT
   - MaximizeHL