name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test genetic
      run: cargo test --verbose -p genetic
    - name: Test grimoire2
      run: cargo test --verbose -p grimoire2
    - name: Test geneticalchemy
      run: cargo test --verbose -p geneticalchemy